# Site settings
title: Courtney's Blog
header-img: img/home-bg.png
email: chalt0319@gmail.com
copyright_name: chalt0319
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  chalt0319
learn_profile: chalt0319
email_username: chalt0319@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
